### ISSUE TITLE
Highlight background color

### ISSUE THREAD

**Issue by fluxxus** [naderi/material-theme-for-brackets#1]
Hi! Really nice work on this theme. Brackets is kinda lacking in themes department, especially when compared to Atom for example. I miss the duotone themes by Simurai on Brackets.

Anyways, back to your theme. IMO the background color when highligting is not very visible. It almost blends with the bg, I am not sure if I selected one word, two words or whole line.

Maybe a minor gripe, but just wanted to let you know my opinion.

**Comment by naderi** [comment]
Hi, thank you for your review. It's corrected now. You can check it after update to the new version.
